#!/bin/bash
#set -eux
set -eu

## for mac osx

# $1=src, $2=dest
function safe_link () {
  base_src="$HOME/dotfiles/"
  base_dest="$HOME/"
  if [ -f "${base_dest}${2}" ]; then
    echo "INFO: exists '${2}'. rename it to '${2}.old'. "
    mv "${base_dest}${2}" "${base_dest}${2}.old"
  fi
  ln -siv "${base_src}${1}" "${base_dest}${2}"
}

# $1=src, $2=dest
function safe_copy () {
  base_src="$HOME/dotfiles/"
  base_dest="$HOME/"
  if [ -f "${base_dest}${2}" ]; then
    echo "INFO: exists '${2}'. rename it to '${2}.old'. "
    mv "${base_dest}${2}" "${base_dest}${2}.old"
  fi
  cp -v "${base_src}${1}" "${base_dest}${2}"
}

# zsh
safe_link "zshrc" ".zshrc"
safe_link "zsh_completions.d" ".zsh_completions.d"
safe_link "zshrc_mac" ".zshrc_mac"

# tmux
safe_link "tmux.conf" ".tmux.conf"
safe_link "tmux_mac.conf" ".tmux_mac.conf"

# emacs
safe_link "emacs.d" ".emacs.d"

# git
safe_link "gitconfig_common" ".gitconfig_common"
safe_copy "gitconfig_template" ".gitconfig"
safe_copy "git-authors" ".git-authors"

# ssh
safe_copy "ssh/config_mac_template" ".ssh/config"
